init:
  - git config --global core.autocrlf input

version: 0.4.{build}

build_script:
  - cmd: build.cmd

test: off

artifacts:
  - path: Build\Packages\*.nupkg

cache:
  - packages -> **\packages.config

services:
  - mssql2014

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

deploy:
  - provider: NuGet
    api_key:
      secure: uiVcx5TSmPy1GGF7GZeoAwXIQTswxvlyo0XKBgaWe1DyzOfJ7Fp3yNimR9IXzUrr
    skip_symbols: false
    on:
      branch: master
  - provider: GitHub
    artifact: /.*\.nupkg/
    auth_token:
      secure: uiVcx5TSmPy1GGF7GZeoAwXIQTswxvlyo0XKBgaWe1DyzOfJ7Fp3yNimR9IXzUrr
    tag: v$(appveyor_build_version)
    draft: false
    prerelease: true
    on:
      branch: master
      appveyor_repo_tag: true
